#GettingToKnowEachother
print('como te llamas?')
print('donde vives?')
print('cual es tu color favorito?')
print('cual es tu comida favorita?')
print('cual es tu hobby?')
print('que te apasiona?')
print('a que lugares te gusta/gustaría ir?')
print('te gustan los deportes?')
print('cual es tu deporte preferido?')
print('cual es tu animal favorito?')